CREATE TABLE IF NOT EXISTS "RH_USUARIOS" (
  "ID"             SERIAL PRIMARY KEY,
  "USERNAME"       VARCHAR(100) NOT NULL,
  "PASSWORD_HASH"  VARCHAR(255) NOT NULL,
  "NOME"           VARCHAR(200) NOT NULL,
  "EMAIL"          VARCHAR(200) NULL,
  "TELEFONE"       VARCHAR(20)  NULL,
  "DTCADASTRO"     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ATIVO"          BOOLEAN      NOT NULL DEFAULT TRUE,
  "ADM"            INT          NOT NULL DEFAULT 0,
  "ID_PROTHEUS"    VARCHAR(50)  NULL,
  CONSTRAINT "UQ_RH_USUARIOS_USERNAME" UNIQUE ("USERNAME")
);

CREATE TABLE IF NOT EXISTS "RH_VAGAS" (
  "ID"                 SERIAL PRIMARY KEY,
  "FUNCAO"             VARCHAR(200) NOT NULL,
  "DATA_ABERTURA"      DATE         NOT NULL,
  "TIPO_VAGA"          VARCHAR(20)  NOT NULL,
  "SOLICITANTE"        VARCHAR(200) NULL,
  "SETOR"              VARCHAR(200) NULL,
  "EMPRESA"            VARCHAR(200) NULL,
  "NOTEBOOK"           CHAR(3)      NOT NULL DEFAULT 'NAO',
  "CELULAR"            CHAR(3)      NOT NULL DEFAULT 'NAO',
  "REQUISITOS_VAGA"    TEXT         NULL,
  "SLA_DIAS"           INT          NULL,
  "CLASSIFICACAO"      VARCHAR(20)  NULL,
  "CANDIDATOS"         INT          NOT NULL DEFAULT 0,
  "ENTREVISTAS"        INT          NOT NULL DEFAULT 0,
  "PRAZO_CONTRATACAO"  DATE         NULL,
  "DT_CONTRATACAO"     DATE         NULL,
  "MATRICULA"          VARCHAR(50)  NULL,
  "STATUS"             VARCHAR(20)  NOT NULL DEFAULT 'ABERTA',
  "USUARIO_CADASTRO"   VARCHAR(50)  NULL,
  "DTINCLUSAO"         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "DTALTERACAO"        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RH_CANDIDATURAS" (
  "ID"              SERIAL PRIMARY KEY,
  "ID_VAGA"         INT          NOT NULL REFERENCES "RH_VAGAS"("ID"),
  "NOME"            VARCHAR(200) NOT NULL,
  "CELULAR"         VARCHAR(20)  NOT NULL,
  "EMAIL"           VARCHAR(200) NOT NULL,
  "LINKEDIN"        VARCHAR(300) NULL,
  "APRESENTACAO"    TEXT         NULL,
  "LINK_ADICIONAL"  VARCHAR(300) NULL,
  "CURRICULO_PATH"  VARCHAR(500) NULL,
  "DTINCLUSAO"      TIMESTAMP    NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RH_ESTOQUE_TI" (
  "ID"            SERIAL PRIMARY KEY,
  "TIPO_PRODUTO"  VARCHAR(50)  NOT NULL,
  "DESCRICAO"     VARCHAR(200) NULL,
  "MODELO"        VARCHAR(200) NULL,
  "DTINCLUSAO"    TIMESTAMP    NULL DEFAULT CURRENT_TIMESTAMP,
  "DTALTERACAO"   TIMESTAMP    NULL DEFAULT CURRENT_TIMESTAMP,
  "QUANTIDADE"    INT          NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS "RH_ESTOQUE_ITENS" (
  "ID"          SERIAL PRIMARY KEY,
  "ID_ESTOQUE"  INT          NOT NULL REFERENCES "RH_ESTOQUE_TI"("ID"),
  "ID_VAGA"     INT          NOT NULL REFERENCES "RH_VAGAS"("ID"),
  "MATRICULA"   VARCHAR(50)  NULL,
  "AREA"        VARCHAR(200) NULL,
  "USUARIO"     VARCHAR(50)  NULL,
  "DTALOCACAO"  TIMESTAMP    NULL DEFAULT CURRENT_TIMESTAMP,
  "STATUS"      VARCHAR(20)  NOT NULL DEFAULT 'DISPONIVEL'
);

CREATE TABLE IF NOT EXISTS "RH_PEDIDOS_COMPRA_TI" (
  "ID"              SERIAL PRIMARY KEY,
  "ID_VAGA"         INT         NOT NULL REFERENCES "RH_VAGAS"("ID"),
  "ITENS_JSON"      TEXT        NOT NULL,
  "STATUS"          VARCHAR(20) NOT NULL DEFAULT 'PENDENTE',
  "OBSERVACOES"     TEXT        NULL,
  "USUARIO_PEDIDO"  VARCHAR(50) NULL,
  "DTPEDIDO"        TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP,
  "DTATUALIZACAO"   TIMESTAMP   NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RH_MERCADO_SUL" (
  "ID"                  SERIAL PRIMARY KEY,
  "FUNCAO_ORIGINAL"     VARCHAR(200)  NOT NULL,
  "CARGO_MERCADO"       VARCHAR(200)  NULL,
  "NIVEL_HIERARQUICO"   VARCHAR(100)  NULL,
  "MEDIA_SALARIAL_PR"   DECIMAL(10,2) NULL,
  "MEDIA_SALARIAL_SUL"  DECIMAL(10,2) NULL,
  "FAIXA_MIN"           DECIMAL(10,2) NULL,
  "FAIXA_MAX"           DECIMAL(10,2) NULL,
  "DTINCLUSAO"          TIMESTAMP     NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS "RH_SLA_CONFIG" (
  "ID"             SERIAL PRIMARY KEY,
  "FUNCAO"         VARCHAR(200) NOT NULL,
  "SLA_DIAS"       INT          NOT NULL,
  "CLASSIFICACAO"  VARCHAR(20)  NOT NULL,
  "DTINCLUSAO"     TIMESTAMP    NULL DEFAULT CURRENT_TIMESTAMP
);
