
CREATE TABLE RH_ESTOQUE_TI (
  ID               INT IDENTITY(1,1) PRIMARY KEY,
  TIPO_PRODUTO     VARCHAR(50)  NOT NULL CHECK (TIPO_PRODUTO IN ('NOTEBOOK','CELULAR','OUTRO')),
  DESCRICAO        VARCHAR(200) NULL,
  MODELO           VARCHAR(200) NULL,
  STATUS           VARCHAR(20)  NOT NULL DEFAULT 'DISPONIVEL'
                   CHECK (STATUS IN ('DISPONIVEL','RESERVADO','EM_USO','MANUTENCAO')),
  DTINCLUSAO       DATETIME     DEFAULT GETDATE(),
  QUANTIDADE       INT          NOT NULL DEFAULT 1,
  DTALTERACAO      DATETIME     DEFAULT GETDATE()
);
GO

CREATE INDEX IX_RH_ESTOQUE_TI_TIPO_STATUS ON RH_ESTOQUE_TI(TIPO_PRODUTO, STATUS);
GO

CREATE TABLE RH_PEDIDOS_COMPRA_TI (
  ID               INT IDENTITY(1,1) PRIMARY KEY,
  ID_VAGA          INT           NOT NULL REFERENCES RH_VAGAS(ID),
  ITENS_JSON       NVARCHAR(MAX) NOT NULL,
  STATUS           VARCHAR(20)   NOT NULL DEFAULT 'PENDENTE'
                   CHECK (STATUS IN ('PENDENTE','ATENDIDO','CANCELADO')),
  OBSERVACOES      VARCHAR(MAX)  NULL,
  USUARIO_PEDIDO   VARCHAR(50)   NULL,
  DTPEDIDO         DATETIME      DEFAULT GETDATE(),
  DTATUALIZACAO    DATETIME      DEFAULT GETDATE()
);
GO

CREATE TABLE RH_ESTOQUE_ITENS (
  ID          INT IDENTITY(1,1) PRIMARY KEY,
  ID_ESTOQUE  INT          NOT NULL REFERENCES RH_ESTOQUE_TI(ID),
  ID_VAGA     INT          NOT NULL REFERENCES RH_VAGAS(ID),
  MATRICULA   VARCHAR(50)  NULL,
  AREA        VARCHAR(200) NULL,
  USUARIO     VARCHAR(50)  NULL,
  DTALOCACAO  DATETIME     DEFAULT GETDATE()
);
GO


