
CREATE TABLE RH_ESTOQUE_TI (
  ID               INT IDENTITY(1,1) PRIMARY KEY,
  TIPO_PRODUTO     VARCHAR(50)  NOT NULL CHECK (TIPO_PRODUTO IN ('NOTEBOOK','CELULAR','OUTRO')),
  DESCRICAO        VARCHAR(200) NULL,
  MODELO           VARCHAR(200) NULL,
  STATUS           VARCHAR(20)  NOT NULL DEFAULT 'DISPONIVEL'
                   CHECK (STATUS IN ('DISPONIVEL','RESERVADO','EM_USO','MANUTENCAO')),
  ID_VAGA          INT          NULL REFERENCES RH_VAGAS(ID),
  AREA             VARCHAR(200) NULL,
  USUARIO_CADASTRO VARCHAR(50)  NULL,
  DTINCLUSAO       DATETIME     DEFAULT GETDATE(),
  DTALTERACAO      DATETIME     DEFAULT GETDATE()
);
GO

CREATE INDEX IX_RH_ESTOQUE_TI_TIPO_STATUS ON RH_ESTOQUE_TI(TIPO_PRODUTO, STATUS);
GO

CREATE TABLE RH_PEDIDOS_COMPRA_TI (
  ID               INT IDENTITY(1,1) PRIMARY KEY,
  ID_VAGA          INT           NOT NULL REFERENCES RH_VAGAS(ID),
  ITENS_JSON       NVARCHAR(MAX) NOT NULL,
  STATUS           VARCHAR(20)   NOT NULL DEFAULT 'PENDENTE'
                   CHECK (STATUS IN ('PENDENTE','ATENDIDO','CANCELADO')),
  OBSERVACOES      VARCHAR(MAX)  NULL,
  USUARIO_PEDIDO   VARCHAR(50)   NULL,
  DTPEDIDO         DATETIME      DEFAULT GETDATE(),
  DTATUALIZACAO    DATETIME      DEFAULT GETDATE()
);
GO

